[tool.black]
line-length = 88
target-version = ['py313']
skip-string-normalization = false

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true